### ISSUE TITLE
How to install compton in qubes?

### ISSUE THREAD

**Issue by N1ck9141** [mohabaks/dotfiles#2]
Hey found you from your Reddit post understand you use Qubes OS? Love your dotfiles, beautiful config, but can see your using Compton? How did you manage to get it installed?

**Comment by mohabaks** [comment]
Hi there. To get compton with qubes I had to used the qubes-builder and build the base kernel.conf to get a working dom0 kernel to chroot (All this is done on my dev-qubes) where I compile the compton and then install only the required dependencies to run on dom0 and transfer the compton binary. Hopeful that helps. Thanks,
