### ISSUE TITLE
Old dotfiles

### ISSUE THREAD

**Issue by Atrate** [mohabaks/dotfiles#5]
Hey there,

I was impressed with your [Qubes OS rice from around 4 years ago](https://old.reddit.com/r/unixporn/comments/eqh7e9/bspwm_qubes_os_feeling_cozy/) but as far as I can see, this repo only goes back 2 years.

I'm interested in the GTK/Qt themes used in that post, could you provide their names?

**Comment by mohabaks** [comment]
Hi, GTK/Qt is Adwaita Dark with custom colors [here](https://github.com/mohabaks/dotfiles/blob/master/.colors/pare)
